version: "3.8"

services:
  app:
    build: .
    container_name: PeerCam
    working_dir: /app
    volumes:
      - ./public:/app/public
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: ["node", "server.js"]
    environment:
      - NODE_ENV=production
    expose:
      - "8080"
    restart: unless-stopped

  apache:
    image: httpd:latest
    container_name: PeerCam_apache
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - certs:/usr/local/apache2/certs
      - ./public:/var/www/certbot
    command: >
      sh -c "cp /usr/local/apache2/conf/httpd.conf /tmp/httpd.conf &&
             sed -i 's/^#ServerName .*/ServerName ${DUCKDNS_DOMAIN}/' /tmp/httpd.conf &&
             httpd-foreground -f /tmp/httpd.conf"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: PeerCam_certbot
    restart: "unless-stopped"
    env_file: .env
    volumes:
      - certs:/etc/letsencrypt
      - ./public:/var/www/certbot
    entrypoint: >
      sh -c "
      echo 'Waiting 15s for Apache to start...' && sleep 15 &&
      certbot certonly --webroot --webroot-path /var/www/certbot -n --agree-tos --email $${EMAIL} -d $${DUCKDNS_DOMAIN}
      "
    depends_on:
      - apache

volumes:
  certs:
